[workspace]
resolver = "2"
members = [
    "agent",
    "alumet",
    "alumet-ffi",
    "plugin-aggregation",
    "plugin-cgroupv1",
    "plugin-cgroupv2",
    "plugin-csv",
    "plugin-energy-attribution",
    "plugin-energy-estimation-tdp",
    "plugin-grace-hopper",
    "plugin-influxdb",
    "plugin-mongodb",
    "plugin-nvidia-nvml",
    "plugin-nvidia-jetson",
    "plugin-perf",
    "plugin-procfs",
    "plugin-prometheus-exporter",
    "plugin-rapl",
    "plugin-relay",
    "plugin-socket-control",
    "plugin-mongodb",
    "plugin-elasticsearch",
    "test-dynamic-plugins", 
    "plugin-example", 
    "plugin-kwollect",
]

# To apply the following lint settings to a workspace member,
# set "lints.workspace" to true in the member's Cargo.toml.
[workspace.lints.clippy]
redundant_field_names = "deny"
needless_return = "deny"
needless_borrow = "deny"
comparison_to_empty = "deny"
single_char_pattern = "deny"
unused_enumerate_index = "deny"
useless_format = "deny"
