[package]
name = "plugin-rapl"
version = "0.3.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
alumet = { path = "../alumet" }
anyhow = "1.0.88"
humantime-serde = "1.1.1"
indoc = "2.0.5"
log = "0.4.22"
perf-event-open-sys2 = "5.0.6"
regex = "1.10.6"
serde = { version = "1.0.210", features = ["derive"] }
once_cell = "1.21.3"

[dev-dependencies]
alumet = {path = "../alumet", features = ["test"]}
toml = "0.8.19"
tempfile = "3.20.0"
nix = "0.30.1"

[lints]
workspace = true
