name: Ensure a clean Git history

on:
  pull_request:

jobs:
  git-checkup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Check that the Git history is linear
        run: |
          BASE_COMMIT=$(git merge-base origin/${{ github.base_ref }} HEAD)
          BASE_REF_SHA=$(git rev-parse origin/${{ github.base_ref }})
          NB_MERGE_COMMITS_ON_BRANCH=$(git rev-list --merges --count ${BASE_COMMIT}..HEAD)

          if [ $NB_MERGE_COMMITS_ON_BRANCH -ne 0 ]; then
            echo "::error::The git history of your branch is non-linear: $NB_MERGE_COMMITS_ON_BRANCH merge commits detected"
            echo "::error::When updating your branch, you must rebase instead of merging."
            exit 1
          elif [ "${BASE_COMMIT}" != "${BASE_REF_SHA}" ]; then 
            echo "::error::The git history of your branch is non-linear: your branch must be rebased on ${{ github.base_ref }}."
            exit 1
          fi
